version: '3'

#networks:
  #proxy:
   # driver: bridge

services:
  web-pinkmoon-01:
    image: cristianodreher/web-pinkmoon:latest
  web-pinkmoon-02:
    image: cristianodreher/web-pinkmoon:latest
      
  web-pinkmoonjeans-01:
    image: cristianodreher/web-pinkmoonjeans:latest
  web-pinkmoonjeans-02:
    image: cristianodreher/web-pinkmoonjeans:latest

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    #networks:
    #  - proxy
  
  
  certbot:
    image: certbot/certbot
     # networks:
    #- proxy
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email cristiano.moraes@crisdu.com.br -d pinkmoonjeans.com.br -d www.pinkmoonjeans.com.br --agree-tos