# Use a imagem oficial do PHP com o servidor Apache embutido
FROM php:8.0-apache

# Copie o arquivo index.php para o diretório padrão do Apache
COPY index.php /var/www/html/

# Exponha a porta 80 para acessar o servidor web
EXPOSE 80

